FROM python:3.12-slim as frontend
WORKDIR /frontend
ADD ./frontend/requirements.txt /frontend/requirements.txt
RUN pip install -r requirements.txt
ADD ./frontend /frontend

EXPOSE 8501
ENV STREAMLIT_SERVER_PORT=8501
#ENV STREAMLIT_BROWSER_SERVERPORT=8501
#ENV STREAMLIT_BROWSER_SERVERADDRESS=localhost

ENTRYPOINT [ "streamlit", "run", "streamlit.py" ]